--
-- PostgreSQL database dump
--

\restrict FQqiceE6ydKhePOKMLuCrWNIdQXxQ3LoQ3cUY1VCUgbFin55EXrXTr6MQXvopg9

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_customuser; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.accounts_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    name character varying(150) NOT NULL,
    role character varying(20) NOT NULL,
    team_id character varying(50),
    avatar character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_customuser OWNER TO legaledge_user;

--
-- Name: accounts_customuser_groups; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.accounts_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_groups OWNER TO legaledge_user;

--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.accounts_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.accounts_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_user_permissions; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.accounts_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_user_permissions OWNER TO legaledge_user;

--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.accounts_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO legaledge_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO legaledge_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO legaledge_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_activity; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_activity (
    id bigint NOT NULL,
    entity character varying(50) NOT NULL,
    entity_id integer,
    action character varying(50) NOT NULL,
    detail text NOT NULL,
    owner character varying(150) NOT NULL,
    at timestamp with time zone NOT NULL,
    team_id character varying(50),
    user_id bigint
);


ALTER TABLE public.crm_activity OWNER TO legaledge_user;

--
-- Name: crm_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_calllog; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_calllog (
    id bigint NOT NULL,
    contact character varying(150) NOT NULL,
    phone character varying(30) NOT NULL,
    duration character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    date date,
    "time" character varying(20) NOT NULL,
    type character varying(10) NOT NULL,
    notes text NOT NULL,
    team_id character varying(50),
    created timestamp with time zone NOT NULL
);


ALTER TABLE public.crm_calllog OWNER TO legaledge_user;

--
-- Name: crm_calllog_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_calllog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_calllog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_company; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_company (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    industry character varying(100) NOT NULL,
    size character varying(50) NOT NULL,
    city character varying(100) NOT NULL,
    website character varying(200) NOT NULL,
    revenue character varying(50) NOT NULL,
    contacts integer NOT NULL,
    deals integer NOT NULL,
    status character varying(20) NOT NULL,
    owner character varying(150) NOT NULL,
    team_id character varying(50),
    created date NOT NULL
);


ALTER TABLE public.crm_company OWNER TO legaledge_user;

--
-- Name: crm_company_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_contact; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_contact (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    company character varying(150) NOT NULL,
    role character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    owner character varying(150) NOT NULL,
    industry character varying(100) NOT NULL,
    priority character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    created date NOT NULL,
    last_contact date,
    team_id character varying(50),
    notes text NOT NULL,
    assigned_to_id bigint
);


ALTER TABLE public.crm_contact OWNER TO legaledge_user;

--
-- Name: crm_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_deal; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_deal (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    company character varying(150) NOT NULL,
    contact character varying(150) NOT NULL,
    value numeric(12,2) NOT NULL,
    stage character varying(20) NOT NULL,
    owner character varying(150) NOT NULL,
    close_date date,
    probability integer NOT NULL,
    created date NOT NULL,
    team_id character varying(50),
    notes text NOT NULL,
    assigned_to_id bigint
);


ALTER TABLE public.crm_deal OWNER TO legaledge_user;

--
-- Name: crm_deal_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_deal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_deal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_designmanagerfile; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_designmanagerfile (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_designmanagerfile OWNER TO legaledge_user;

--
-- Name: crm_designmanagerfile_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_designmanagerfile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_designmanagerfile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_emailmessagerecord; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_emailmessagerecord (
    id bigint NOT NULL,
    folder character varying(20) NOT NULL,
    provider character varying(20) NOT NULL,
    from_email character varying(254) NOT NULL,
    to_email character varying(254) NOT NULL,
    cc text NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    unread boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL,
    direction character varying(20) NOT NULL,
    external_id character varying(255) NOT NULL,
    in_reply_to character varying(255) NOT NULL,
    received_at timestamp with time zone,
    snippet text NOT NULL,
    synced_at timestamp with time zone,
    thread_id character varying(255) NOT NULL,
    account_id bigint,
    is_read boolean NOT NULL,
    receiver_id bigint,
    receiver_email character varying(254),
    sender_id bigint,
    sender_email character varying(254)
);


ALTER TABLE public.crm_emailmessagerecord OWNER TO legaledge_user;

--
-- Name: crm_emailmessagerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_emailmessagerecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_emailmessagerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_lead; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_lead (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    company character varying(150) NOT NULL,
    source character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    owner character varying(150) NOT NULL,
    value character varying(50) NOT NULL,
    temperature character varying(10) NOT NULL,
    industry character varying(100) NOT NULL,
    notes text NOT NULL,
    created date NOT NULL,
    team_id character varying(50),
    assigned_to_id bigint
);


ALTER TABLE public.crm_lead OWNER TO legaledge_user;

--
-- Name: crm_lead_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_lead ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_lead_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingad; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingad (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingad OWNER TO legaledge_user;

--
-- Name: crm_marketingad_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingbuyerintent; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingbuyerintent (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingbuyerintent OWNER TO legaledge_user;

--
-- Name: crm_marketingbuyerintent_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingbuyerintent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingbuyerintent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingcampaign; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingcampaign (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingcampaign OWNER TO legaledge_user;

--
-- Name: crm_marketingcampaign_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingcampaign ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingcampaign_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingevent; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingevent (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingevent OWNER TO legaledge_user;

--
-- Name: crm_marketingevent_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingform; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingform (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingform OWNER TO legaledge_user;

--
-- Name: crm_marketingform_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingleadscoring; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingleadscoring (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingleadscoring OWNER TO legaledge_user;

--
-- Name: crm_marketingleadscoring_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingleadscoring ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingleadscoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_marketingsocialpost; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_marketingsocialpost (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    payload jsonb NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_marketingsocialpost OWNER TO legaledge_user;

--
-- Name: crm_marketingsocialpost_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_marketingsocialpost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_marketingsocialpost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_meeting; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_meeting (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    type character varying(20) NOT NULL,
    date date,
    "time" character varying(20) NOT NULL,
    contact character varying(150) NOT NULL,
    duration character varying(20) NOT NULL,
    platform character varying(20) NOT NULL,
    notes text NOT NULL,
    team_id character varying(50),
    created timestamp with time zone NOT NULL
);


ALTER TABLE public.crm_meeting OWNER TO legaledge_user;

--
-- Name: crm_meeting_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_meeting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_meeting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_note; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_note (
    id bigint NOT NULL,
    local_id character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    owner character varying(150) NOT NULL,
    team_id character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.crm_note OWNER TO legaledge_user;

--
-- Name: crm_note_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_task; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_task (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    type character varying(20) NOT NULL,
    priority character varying(20) NOT NULL,
    due_date date,
    status character varying(20) NOT NULL,
    owner character varying(150) NOT NULL,
    related character varying(250) NOT NULL,
    notes text NOT NULL,
    team_id character varying(50),
    created timestamp with time zone NOT NULL,
    assigned_to_id bigint
);


ALTER TABLE public.crm_task OWNER TO legaledge_user;

--
-- Name: crm_task_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_ticket; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_ticket (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    contact character varying(150) NOT NULL,
    company character varying(150) NOT NULL,
    priority character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    category character varying(50) NOT NULL,
    owner character varying(150) NOT NULL,
    team_id character varying(50),
    created date NOT NULL,
    notes text NOT NULL
);


ALTER TABLE public.crm_ticket OWNER TO legaledge_user;

--
-- Name: crm_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_useremailaccount; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.crm_useremailaccount (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    email_address character varying(254) NOT NULL,
    access_token text NOT NULL,
    refresh_token text NOT NULL,
    token_expiry timestamp with time zone,
    scope text NOT NULL,
    external_account_id character varying(255) NOT NULL,
    sync_cursor character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.crm_useremailaccount OWNER TO legaledge_user;

--
-- Name: crm_useremailaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.crm_useremailaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_useremailaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO legaledge_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO legaledge_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO legaledge_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: legaledge_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: legaledge_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO legaledge_user;

--
-- Data for Name: accounts_customuser; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.accounts_customuser (id, password, last_login, is_superuser, email, name, role, team_id, avatar, is_active, is_staff, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$IKDE4EdGlKcwDYHaeUwIyM$P6DgdXtwNbglCxzpOsD3kkmZ8ITiixNRKUVVCnovlW4=	2026-03-23 22:05:57.24+05:30	t	shailesh@legaledge.in	Shailesh Bhange	admin	\N	SB	t	t	2026-03-23 14:40:03.315+05:30
2	pbkdf2_sha256$1200000$vylJK0tMbvrSZwTOrDInLx$oCLyyjQtYQd4hu5xE91EVS9tnunbh2JzFd9CtQhUzdQ=	\N	f	arjun@legaledge.in	Arjun Mehta	manager	team_01	AM	t	f	2026-03-23 14:40:06.704+05:30
3	pbkdf2_sha256$1200000$w90EfmxvWw8rXvEG3q7uxR$UMh4Mo+TQgOsWxOsJBe5bfSe9Ob0fXNaKZUhksRcR+s=	\N	f	priya@legaledge.in	Priya Sharma	user	team_01	PS	t	f	2026-03-23 14:40:10.564+05:30
5	pbkdf2_sha256$1000000$Q63RhRs8gv4hT4CaM6Rywe$XXo/diVRUTT8sZFdqIlSTpG1dXP7SHlrn4G/8MDdcbY=	\N	f	neha@legaledge.in	Neha Singh	user	team_02	NS	t	f	2026-03-23 14:40:20.052+05:30
6	pbkdf2_sha256$1000000$9dHmMKxCtwSr4T7XM7HNFU$5cky8eQ8D/6NHGXisIp7ec05DZOZS0QD7VyCP0dwJ7A=	\N	f	aman@legaledge.in	Aman Jha	user	team_02	AJ	t	f	2026-03-23 14:40:25.221+05:30
7	pbkdf2_sha256$1200000$4Olgm1K4hJoJxltKLX6g1a$JBoAbryUSpc0IOhqHhrTaGqyRHwXy3tiHrXiE1V4hsU=	2026-03-30 18:04:18.777+05:30	t	ramp@gmail.com	ram	admin	\N	R	t	t	2026-03-23 15:05:08.881+05:30
8	pbkdf2_sha256$1200000$IozTpzCZ21qGso1cM8UnFt$jpqhqNqa8pOJsn+WmDYsq0bR9rFdOvit9Ui7Ea7RwoY=	\N	f	smtp.sender@test.local	SMTP Sender	user	\N	SS	t	f	2026-03-24 22:38:03.23+05:30
9	pbkdf2_sha256$1200000$yU3mcWrGsvJNqyWd45tIxY$+QYrAhnyqsMKyc7txiOoVZ6p69vBXgDBdohQj+jKYXA=	\N	f	smtp.receiver@test.local	SMTP Receiver	user	\N	SR	t	f	2026-03-24 22:38:07.771+05:30
4	pbkdf2_sha256$1200000$OqzojPaxHodf084iE3rY2m$jU23jWBTR7pPDN3PthpIokBtwa9ZdL6wg4Jsh5imBkY=	\N	f	rohan@legaledge.in	Rohan Verma	user	team_01	RV	t	f	2026-03-23 14:40:14.859+05:30
\.


--
-- Data for Name: accounts_customuser_groups; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.accounts_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.accounts_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add User	6	add_customuser
22	Can change User	6	change_customuser
23	Can delete User	6	delete_customuser
24	Can view User	6	view_customuser
25	Can add call log	8	add_calllog
26	Can change call log	8	change_calllog
27	Can delete call log	8	delete_calllog
28	Can view call log	8	view_calllog
29	Can add company	9	add_company
30	Can change company	9	change_company
31	Can delete company	9	delete_company
32	Can view company	9	view_company
33	Can add meeting	22	add_meeting
34	Can change meeting	22	change_meeting
35	Can delete meeting	22	delete_meeting
36	Can view meeting	22	view_meeting
37	Can add ticket	25	add_ticket
38	Can change ticket	25	change_ticket
39	Can delete ticket	25	delete_ticket
40	Can view ticket	25	view_ticket
41	Can add activity	7	add_activity
42	Can change activity	7	change_activity
43	Can delete activity	7	delete_activity
44	Can view activity	7	view_activity
45	Can add contact	10	add_contact
46	Can change contact	10	change_contact
47	Can delete contact	10	delete_contact
48	Can view contact	10	view_contact
49	Can add deal	11	add_deal
50	Can change deal	11	change_deal
51	Can delete deal	11	delete_deal
52	Can view deal	11	view_deal
53	Can add lead	14	add_lead
54	Can change lead	14	change_lead
55	Can delete lead	14	delete_lead
56	Can view lead	14	view_lead
57	Can add task	24	add_task
58	Can change task	24	change_task
59	Can delete task	24	delete_task
60	Can view task	24	view_task
61	Can add design manager file	12	add_designmanagerfile
62	Can change design manager file	12	change_designmanagerfile
63	Can delete design manager file	12	delete_designmanagerfile
64	Can view design manager file	12	view_designmanagerfile
65	Can add marketing ad	15	add_marketingad
66	Can change marketing ad	15	change_marketingad
67	Can delete marketing ad	15	delete_marketingad
68	Can view marketing ad	15	view_marketingad
69	Can add marketing buyer intent	16	add_marketingbuyerintent
70	Can change marketing buyer intent	16	change_marketingbuyerintent
71	Can delete marketing buyer intent	16	delete_marketingbuyerintent
72	Can view marketing buyer intent	16	view_marketingbuyerintent
73	Can add marketing campaign	17	add_marketingcampaign
74	Can change marketing campaign	17	change_marketingcampaign
75	Can delete marketing campaign	17	delete_marketingcampaign
76	Can view marketing campaign	17	view_marketingcampaign
77	Can add marketing event	18	add_marketingevent
78	Can change marketing event	18	change_marketingevent
79	Can delete marketing event	18	delete_marketingevent
80	Can view marketing event	18	view_marketingevent
81	Can add marketing form	19	add_marketingform
82	Can change marketing form	19	change_marketingform
83	Can delete marketing form	19	delete_marketingform
84	Can view marketing form	19	view_marketingform
85	Can add marketing lead scoring	20	add_marketingleadscoring
86	Can change marketing lead scoring	20	change_marketingleadscoring
87	Can delete marketing lead scoring	20	delete_marketingleadscoring
88	Can view marketing lead scoring	20	view_marketingleadscoring
89	Can add marketing social post	21	add_marketingsocialpost
90	Can change marketing social post	21	change_marketingsocialpost
91	Can delete marketing social post	21	delete_marketingsocialpost
92	Can view marketing social post	21	view_marketingsocialpost
93	Can add note	23	add_note
94	Can change note	23	change_note
95	Can delete note	23	delete_note
96	Can view note	23	view_note
97	Can add email message record	13	add_emailmessagerecord
98	Can change email message record	13	change_emailmessagerecord
99	Can delete email message record	13	delete_emailmessagerecord
100	Can view email message record	13	view_emailmessagerecord
101	Can add user email account	26	add_useremailaccount
102	Can change user email account	26	change_useremailaccount
103	Can delete user email account	26	delete_useremailaccount
104	Can view user email account	26	view_useremailaccount
\.


--
-- Data for Name: crm_activity; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_activity (id, entity, entity_id, action, detail, owner, at, team_id, user_id) FROM stdin;
\.


--
-- Data for Name: crm_calllog; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_calllog (id, contact, phone, duration, status, date, "time", type, notes, team_id, created) FROM stdin;
1	Rahul Sharma	+91-9876543210	8:32	Answered	2026-03-10	10:15 AM	Outbound	Discussed enterprise pricing	team_01	2026-03-23 14:40:30.476+05:30
2	Priya Mehta	+91-9871234560	3:45	Missed	2026-03-10	11:30 AM	Inbound		team_01	2026-03-23 14:40:30.476+05:30
3	Amit Joshi	+91-9823456781	12:08	Answered	2026-03-09	02:00 PM	Outbound	Demo scheduled for next week	team_01	2026-03-23 14:40:30.476+05:30
4	Meera Nair	+91-9912345678	5:20	Answered	2026-03-08	04:30 PM	Outbound	Contract review discussed	team_02	2026-03-23 14:40:30.477+05:30
\.


--
-- Data for Name: crm_company; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_company (id, name, industry, size, city, website, revenue, contacts, deals, status, owner, team_id, created) FROM stdin;
1	TechCorp India	Technology	500-1000	Mumbai	techcorp.in	50 Cr	3	2	Customer	Shailesh Bhange	team_01	2026-03-23
2	Legal Solutions Ltd	Legal	50-200	Delhi	legalsolutions.in	15 Cr	2	1	Prospect	Arjun Mehta	team_01	2026-03-23
3	FinPro Services	Finance	200-500	Pune	finpro.in	30 Cr	1	1	Customer	Arjun Mehta	team_01	2026-03-23
4	MediCare Group	Healthcare	1000+	Hyderabad	medicare.in	200 Cr	2	2	Customer	Shailesh Bhange	\N	2026-03-23
5	RetailCo India	Retail	100-500	Ahmedabad	retailco.in	80 Cr	1	1	Lead	Arjun Mehta	team_02	2026-03-23
\.


--
-- Data for Name: crm_contact; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_contact (id, name, email, phone, company, role, city, status, owner, industry, priority, type, created, last_contact, team_id, notes, assigned_to_id) FROM stdin;
1	Rahul Sharma	rahul.sharma@techcorp.in	+91-9876543210	TechCorp India	CEO	Mumbai	active	Shailesh Bhange	Technology	High	Customer	2026-03-23	\N	team_01		3
2	Priya Mehta	priya@legalsolutions.in	+91-9871234560	Legal Solutions Ltd	Partner	Delhi	active	Arjun Mehta	Legal	High	Lead	2026-03-23	\N	team_01		3
3	Amit Joshi	amit.joshi@finpro.in	+91-9823456781	FinPro Services	CFO	Pune	active	Arjun Mehta	Finance	Medium	Customer	2026-03-23	\N	team_01		4
4	Sunita Verma	sunita@medicare.in	+91-9756789012	MediCare Group	Director	Hyderabad	inactive	Shailesh Bhange	Healthcare	Low	Prospect	2026-03-23	\N	\N		1
5	Karan Patel	karan.patel@retailco.in	+91-9845671234	RetailCo India	Manager	Ahmedabad	active	Arjun Mehta	Retail	Medium	Lead	2026-03-23	\N	team_02		5
6	Meera Nair	meera@constructpro.in	+91-9912345678	ConstructPro	VP Sales	Bangalore	active	Arjun Mehta	Construction	High	Customer	2026-03-23	\N	team_02		6
7	Sakshi patil	sakship@gmail.com	9876543211	kavya	java devloper	pune	active	Nainika Pounikar	Healthcare	Medium	Customer	2026-03-23	\N	\N		\N
8	Yash Nikhare	yash@legaledge.com	8625910833	media	Content Writer	Nagpur	active	Nainika Pounikar	Technology	Low	Lead	2026-03-23	\N	\N		\N
10	Test User	test@example.com	1234567890	Test Corp	Manager		active	Nainika Pounikar		Medium	Lead	2026-03-24	\N	\N		\N
11	Nainika Pounikar	nainikapounikar16@gmail.com	8625910833	techinfo	Software developer	Nagpur	active	Nainika Pounikar	Legal	Medium	Lead	2026-03-25	\N	\N		\N
12	Navya  Sharma	navya@legaledge.in	8625910833	Tech Info	Developer	Nagpur	active	Nainika Pounikar	Technology	Medium	Lead	2026-03-28	\N	\N		\N
13	Nainika Pounikar	nainikapounikar16@gmail.com	8625910833	TechInfo	CEO	Nagpur	active	Nainika Pounikar	Technology	Medium	Lead	2026-03-30	\N	\N		\N
14	Aarohi Pounikar	nainikapounikar16@gmail.com	8625910833	InfoPharma	CEO	Nagpur	active	Nainika Pounikar		Medium	Lead	2026-03-31	\N	\N		\N
\.


--
-- Data for Name: crm_deal; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_deal (id, name, company, contact, value, stage, owner, close_date, probability, created, team_id, notes, assigned_to_id) FROM stdin;
1	Legal Suite Enterprise	TechCorp India	Rahul Sharma	500000.00	Negotiation	Shailesh Bhange	2026-03-31	90	2026-03-23	team_01		3
2	CRM Starter Pack	Legal Solutions Ltd	Priya Mehta	150000.00	Proposal	Arjun Mehta	2026-04-15	50	2026-03-23	team_01		3
3	Analytics Dashboard	FinPro Services	Amit Joshi	280000.00	Contacted	Arjun Mehta	2026-04-30	30	2026-03-23	team_01		4
4	Premium Support Plan	MediCare Group	Sunita Verma	120000.00	Closed Won	Shailesh Bhange	2026-02-28	100	2026-03-23	\N		1
5	Basic CRM License	RetailCo India	Karan Patel	60000.00	New Lead	Arjun Mehta	2026-05-01	20	2026-03-23	team_02		5
6	Full Platform Bundle	ConstructPro	Meera Nair	750000.00	Proposal	Arjun Mehta	2026-04-20	60	2026-03-23	team_02		6
7	Audit Module	Singh & Associates	Deepa Singh	90000.00	Closed Lost	Arjun Mehta	2026-02-15	0	2026-03-23	team_01		3
8	helthcare	kavya	9876553432	120000.00	Contacted	Nainika Pounikar	\N	50	2026-03-23	\N		\N
\.


--
-- Data for Name: crm_designmanagerfile; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_designmanagerfile (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_emailmessagerecord; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_emailmessagerecord (id, folder, provider, from_email, to_email, cc, subject, body, unread, created_at, owner_id, direction, external_id, in_reply_to, received_at, snippet, synced_at, thread_id, account_id, is_read, receiver_id, receiver_email, sender_id, sender_email) FROM stdin;
1	inbox	internal	smtp.sender@test.local	smtp.receiver@test.local		Internal test	Internal path check	t	2026-03-24 22:38:07.805+05:30	9	inbound			2026-03-24 22:38:07.802+05:30	Internal path check	2026-03-24 22:38:07.802+05:30		\N	f	9	smtp.receiver@test.local	8	smtp.sender@test.local
2	sent	internal	smtp.sender@test.local	smtp.receiver@test.local		Internal test	Internal path check	f	2026-03-24 22:38:07.83+05:30	8	outbound			2026-03-24 22:38:07.829+05:30	Internal path check	2026-03-24 22:38:07.829+05:30		\N	t	9	smtp.receiver@test.local	8	smtp.sender@test.local
3	sent	gmail	arunpounikar3@gmail.com	nainikapounikar16@gmail.com		Following up on our conversation	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need any clarification.\n\nLooking forward to hearing from you.\n\nBest regards	f	2026-03-25 10:20:53.08+05:30	1	outbound			2026-03-25 10:20:53.078+05:30	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need an	2026-03-25 10:20:53.078+05:30	smtp-cfa4c3d715734f3a99566d64469df7e9	\N	t	\N	nainikapounikar16@gmail.com	1	shailesh@legaledge.in
5	sent	gmail	arunpounikar3@gmail.com	nainikapounikar16@gmail.com		Following up on our conversation	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need any clarification.\n\nLooking forward to hearing from you.\n\nBest regards	f	2026-03-25 10:20:55.724+05:30	1	outbound			2026-03-25 10:20:55.721+05:30	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need an	2026-03-25 10:20:55.721+05:30	smtp-b82c70b466d346d78a69ef92619ec977	\N	t	\N	nainikapounikar16@gmail.com	1	shailesh@legaledge.in
6	sent	gmail	arunpounikar3@gmail.com	nainikapounikar16@gmail.com		Following up on our conversation	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need any clarification.\n\nLooking forward to hearing from you.\n\nBest regards	f	2026-03-25 10:20:55.918+05:30	1	outbound			2026-03-25 10:20:55.917+05:30	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need an	2026-03-25 10:20:55.917+05:30	smtp-d434abc5ab8f415e9c30fb179d711027	\N	t	\N	nainikapounikar16@gmail.com	1	shailesh@legaledge.in
7	sent	gmail	arunpounikar3@gmail.com	nainikapounikar16@gmail.com		LegalEdge CRM Proposal	Hi,\n\nThank you for your interest in LegalEdge CRM. Please find below the proposal details tailored to your requirements.\n\nOur solution includes:\n- Complete CRM platform\n- Dedicated onboarding support\n- 24/7 customer service\n\nWe'd love to schedule a quick call to walk you through the details.\n\nBest regards\n\nBest regards,\nShailesh Bhange	f	2026-03-25 11:16:50.492+05:30	1	outbound			2026-03-25 11:16:50.49+05:30	Hi,\n\nThank you for your interest in LegalEdge CRM. Please find below the proposal details tailored to your requirements.\n\nOur solution includes:\n- Complete CRM platform\n- Dedicated	2026-03-25 11:16:50.49+05:30	smtp-56a88470af834601bf415fb0e9ac0ab7	\N	t	\N	nainikapounikar16@gmail.com	1	shailesh@legaledge.in
8	sent	gmail	arunpounikar3@gmail.com	rahul.sharma@techcorp.in		Following up on our conversation	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need any clarification.\n\nLooking forward to hearing from you.\n\nBest regards	f	2026-03-25 12:49:58.1+05:30	3	outbound			2026-03-25 12:49:58.095+05:30	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need an	2026-03-25 12:49:58.095+05:30	smtp-92474cbca29d402b899f06f320c653a2	\N	t	\N	rahul.sharma@techcorp.in	3	priya@legaledge.in
9	sent	gmail	arunpounikar3@gmail.com	rushigade0707@gmail.com	nainikapounikar16@gmail.com	Following up on our conversation	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need any clarification.\n\nLooking forward to hearing from you.\n\nBest regards	f	2026-03-25 17:45:32.936+05:30	1	outbound			2026-03-25 17:45:32.933+05:30	Hi,\n\nI wanted to follow up on our recent conversation and check if you had a chance to review the information we discussed.\n\nPlease let me know if you have any questions or need an	2026-03-25 17:45:32.933+05:30	smtp-add57998503a40868935ea0bf6de4257	\N	t	\N	rushigade0707@gmail.com	1	shailesh@legaledge.in
\.


--
-- Data for Name: crm_lead; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_lead (id, name, email, phone, company, source, status, owner, value, temperature, industry, notes, created, team_id, assigned_to_id) FROM stdin;
1	Vijay Khanna	vijay@startupx.in	+91-9867890123	StartupX	Website	New	Shailesh Bhange	2,50,000	Hot	Technology	Interested in enterprise plan	2026-03-23	team_01	3
2	Deepa Singh	deepa@lawfirm.in	+91-9823456780	Singh & Associates	Referral	Contacted	Arjun Mehta	1,80,000	Warm	Legal	Follow-up scheduled	2026-03-23	team_01	3
3	Rajesh Kumar	rajesh@mfgco.in	+91-9756780123	MfgCo Industries	LinkedIn	Qualified	Arjun Mehta	5,00,000	Hot	Manufacturing	Budget approved	2026-03-23	team_01	4
4	Ananya Bose	ananya@edutech.in	+91-9845670123	EduTech Solutions	Email Campaign	New	Shailesh Bhange	75,000	Cold	Education	Initial inquiry	2026-03-23	\N	1
5	Sachin Pawar	sachin@healthplus.in	+91-9912340678	HealthPlus	Event	Negotiation	Arjun Mehta	3,50,000	Warm	Healthcare	Pricing discussion	2026-03-23	team_02	5
6	Rahul S	rahul.s@team1.in	9876543210	TechCorp	Referral	New	Priya Sharma	1,00,000	Warm	Technology	Via colleague referral	2026-03-23	team_01	3
7	Priya Desai	priya.d@team1.in	9123456780	Desai Law	Website	Contacted	Priya Sharma	80,000	Warm	Legal	Wants consultation	2026-03-23	team_01	3
8	Vikram Nair	vikram@team1.in	9988776655	Nair Group	Ads	Qualified	Rohan Verma	2,20,000	Hot	Finance	Demo scheduled	2026-03-23	team_01	4
9	Anita Kapoor	anita@team2.in	9765432100	Kapoor Inc	Referral	Won	Neha Singh	1,50,000	Hot	Retail	Closed successfully	2026-03-23	team_02	5
10	Suresh Pillai	suresh@team2.in	9654321098	Pillai Mfg	Cold Call	Lost	Aman Jha	50,000	Cold	Manufacturing	Budget constraint	2026-03-23	team_02	6
11	Rahul	rahul@legaledge.com	9970627510	Legal Edge	Website	Contacted	Nainika Pounikar	56000	Hot	Retail	Hello..	2026-03-23	team_01	2
12	Rushikesh	rushi@legaledge.com	9960452344	Legal Edge	Website	Qualified	Nainika Pounikar	45600	Hot	Real Estate	Hello..	2026-03-24	team_01	2
13	Rushi	rushi@legaledge.com	8625910833	Techinfo	Referral	Contacted	Nainika Pounikar	450000	Warm	Real Estate	Hello	2026-03-24	team_01	2
14	Priya Sharma	priya@legaledge.com	9970627510	Technobase	Website	Qualified	Nainika Pounikar	670000	Hot	Real Estate	Project Leads	2026-03-24	team_01	2
15	navya	navya@legaledge.in	9876543221	infoweb	LinkedIn	Contacted	Nainika Pounikar	65000	Hot	Education	Discuss the Bussiness	2026-03-25	team_01	2
\.


--
-- Data for Name: crm_marketingad; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingad (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_marketingbuyerintent; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingbuyerintent (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_marketingcampaign; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingcampaign (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
1	1774428305353	{"id": "1774428305353", "name": "Master Project", "type": "email", "status": "Active", "createdDate": "25 Mar 2026", "description": "Working on the Campgien related work"}	team_01	2026-03-25 14:15:05.836+05:30	2026-03-25 14:15:05.837+05:30	2
\.


--
-- Data for Name: crm_marketingevent; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingevent (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_marketingform; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingform (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
1	1774376032106	{"id": "1774376032106", "name": "Demo Request", "type": "Contact Us", "notes": "", "owner": "Nainika", "status": "Active", "recaptcha": false, "emailNotif": true, "createdDate": "24 Mar 2026", "gdprConsent": true, "linkedCampaign": "Q1 Campaign", "targetAudience": "B2B", "afterSubmission": "Show Thank-You Message"}	\N	2026-03-24 23:43:52.175+05:30	2026-03-24 23:43:52.175+05:30	1
\.


--
-- Data for Name: crm_marketingleadscoring; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingleadscoring (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_marketingsocialpost; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_marketingsocialpost (id, local_id, payload, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_meeting; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_meeting (id, title, type, date, "time", contact, duration, platform, notes, team_id, created) FROM stdin;
1	Product Demo - TechCorp	Video Call	2026-03-12	11:00 AM	Rahul Sharma	1 hour	zoom	Full platform demo	team_01	2026-03-23 14:40:30.504+05:30
2	Pricing Discussion - FinPro	Meeting	2026-03-14	03:00 PM	Amit Joshi	45 min	gmeet	Discuss enterprise pricing	team_01	2026-03-23 14:40:30.504+05:30
3	Onboarding Kickoff - MediCare	Video Call	2026-03-18	10:00 AM	Sunita Verma	1 hour	teams	Welcome and setup	\N	2026-03-23 14:40:30.505+05:30
5	E2E Check Meeting	Meeting	2026-03-23	19:10	E2E Contact	30 mins	zoom	Created by e2e check	\N	2026-03-23 19:01:12.715+05:30
7	Healthcare Project Bussiness Meeting	Meeting	2026-03-23	21:24	Rakul Preet	30 mins	gmeet	Discuss about appointments	\N	2026-03-23 19:24:36.577+05:30
8	Healthcare Bussiness	Meeting	2026-03-23	20:40	Riya Kapoor	30 mins	gmeet	Disscuss About doctoor appointments	\N	2026-03-23 19:40:20.909+05:30
9	Project Hospital Management	Meeting	2026-03-23	23:34	Rahul Verma	30 mins	gmeet	Discuss Project	\N	2026-03-23 22:32:54.516+05:30
10	Project Meeting	Meeting	2026-03-24	14:49	Navya	30 mins	gmeet	Discuss Meeting	\N	2026-03-24 12:48:16.557+05:30
11	Medical Project	Meeting	2026-03-24	16:01	Navya Sharma	1 hour	gmeet	Discuss about medicines	\N	2026-03-24 14:01:47.416+05:30
12	Project Details	Meeting	2026-03-24	22:54	Navya Sharma	30 mins	gmeet	Discuss about Business flow	\N	2026-03-24 20:55:12.383+05:30
13	Project Meeting	Meeting	2026-03-25	12:30	Nitin Raut	1 hour	gmeet	Discuss about project	\N	2026-03-25 10:29:11.532+05:30
14	Teams Meet	Meeting	2026-03-25	18:30	Navya Sharma	1 hour	teams	Discuss about CRM project	\N	2026-03-25 13:25:28.623+05:30
15	Project Meet	Meeting	2026-03-26	20:44	Nainika Pounikar	30 mins	gmeet	Discuss about CRM project	\N	2026-03-25 18:41:39.89+05:30
16	Project CRM	Meeting	2026-03-28	18:04	Ojasvi Pounikar	30 mins	gmeet	Discuss about bussiness	\N	2026-03-28 15:04:23.542+05:30
17	Project CRM	Meeting	2026-03-30	19:30	Navya Sharma	30 mins	gmeet	Discuss all the CRM Issue	\N	2026-03-30 17:30:58.237+05:30
18	Project CRM	Meeting	2026-03-31	19:05	Nitin Deshmukh	30 mins	gmeet	Discuss About CRM	\N	2026-03-30 18:06:09.407+05:30
\.


--
-- Data for Name: crm_note; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_note (id, local_id, title, description, owner, team_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: crm_task; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_task (id, title, type, priority, due_date, status, owner, related, notes, team_id, created, assigned_to_id) FROM stdin;
1	Follow-up call with Priya Mehta	Call	High	2026-03-15	Completed	Shailesh Bhange	Lead: Priya Mehta	Discuss enterprise pricing	team_01	2026-03-23 14:40:30.386+05:30	3
2	Send proposal to TechCorp	Email	High	2026-03-16	Completed	Arjun Mehta	Deal: Legal Suite Enterprise	Include case studies	team_01	2026-03-23 14:40:30.386+05:30	3
3	Schedule demo with FinPro	Meeting	Medium	2026-03-17	Completed	Arjun Mehta	Contact: Amit Joshi	Analytics dashboard demo	team_01	2026-03-23 14:40:30.386+05:30	4
4	Contract review - MediCare	Document	Low	2026-03-20	Completed	Shailesh Bhange	Deal: Premium Support Plan	Final sign-off	\N	2026-03-23 14:40:30.386+05:30	1
5	LinkedIn outreach - EduTech	Email	Medium	2026-03-18	Completed	Arjun Mehta	Lead: Ananya Bose	Connect and share brochure	team_02	2026-03-23 14:40:30.386+05:30	5
6	Site visit - ConstructPro	Meeting	High	2026-03-19	Completed	Arjun Mehta	Deal: Full Platform Bundle	Meet VP Sales team	team_02	2026-03-23 14:40:30.386+05:30	6
7	Follow-up call with Rahul	Call	High	2026-03-15	Completed	Priya Sharma	Lead: Rahul S		team_01	2026-03-23 14:40:30.387+05:30	3
8	Send retainer draft to Priya Desai	Document	High	2026-03-15	Completed	Priya Sharma	Lead: Priya Desai		team_01	2026-03-23 14:40:30.387+05:30	3
9	Update case notes - Anita	Document	Medium	2026-03-15	Completed	Priya Sharma	Lead: Anita Kapoor		team_01	2026-03-23 14:40:30.387+05:30	3
10	E2E Check Task	Call	High	2026-03-24	Completed	E2E Runner	E2E	Created by e2e check	\N	2026-03-23 19:01:13.015+05:30	\N
12	Follow-up with Riya	Email	High	2026-03-23	Completed	Nainika Pounikar	Bussiness	Hello.. connect as soon as possible	\N	2026-03-23 19:25:59.119+05:30	1
13	Follow-up Meeting	Call	High	2026-03-24	In Progress	Nainika Pounikar	Project	Project Advice	team_01	2026-03-24 15:02:03.497+05:30	2
\.


--
-- Data for Name: crm_ticket; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_ticket (id, title, contact, company, priority, status, category, owner, team_id, created, notes) FROM stdin;
1	Cannot login to CRM	Rahul Sharma	TechCorp India	High	Open	Technical	Shailesh Bhange	team_01	2026-03-23	
2	Invoice discrepancy	Priya Mehta	Legal Solutions Ltd	Medium	In Progress	Billing	Arjun Mehta	team_01	2026-03-23	
3	Feature request - bulk import	Amit Joshi	FinPro Services	Low	Open	Feature Request	Arjun Mehta	team_01	2026-03-23	
4	API integration help	Meera Nair	ConstructPro	High	Closed	Technical	Shailesh Bhange	team_02	2026-03-23	
5	Cannot login to CRM	8625910833	TechInfo	Medium	Open	Technical	Siddehesh Waske	\N	2026-03-31	
6	Cannot login to CRM	8625910833	Infobeat	Medium	Open	Technical	Nainika Pounikar	\N	2026-03-31	
\.


--
-- Data for Name: crm_useremailaccount; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.crm_useremailaccount (id, provider, email_address, access_token, refresh_token, token_expiry, scope, external_account_id, sync_cursor, is_active, last_synced_at, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	customuser
7	crm	activity
8	crm	calllog
9	crm	company
10	crm	contact
11	crm	deal
12	crm	designmanagerfile
13	crm	emailmessagerecord
14	crm	lead
15	crm	marketingad
16	crm	marketingbuyerintent
17	crm	marketingcampaign
18	crm	marketingevent
19	crm	marketingform
20	crm	marketingleadscoring
21	crm	marketingsocialpost
22	crm	meeting
23	crm	note
24	crm	task
25	crm	ticket
26	crm	useremailaccount
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-31 12:15:56.689728+05:30
2	contenttypes	0002_remove_content_type_name	2026-03-31 12:15:56.70793+05:30
3	auth	0001_initial	2026-03-31 12:15:56.82013+05:30
4	auth	0002_alter_permission_name_max_length	2026-03-31 12:15:56.827676+05:30
5	auth	0003_alter_user_email_max_length	2026-03-31 12:15:56.835159+05:30
6	auth	0004_alter_user_username_opts	2026-03-31 12:15:56.842002+05:30
7	auth	0005_alter_user_last_login_null	2026-03-31 12:15:56.851457+05:30
8	auth	0006_require_contenttypes_0002	2026-03-31 12:15:56.853765+05:30
9	auth	0007_alter_validators_add_error_messages	2026-03-31 12:15:56.860709+05:30
10	auth	0008_alter_user_username_max_length	2026-03-31 12:15:56.867835+05:30
11	auth	0009_alter_user_last_name_max_length	2026-03-31 12:15:56.876726+05:30
12	auth	0010_alter_group_name_max_length	2026-03-31 12:15:56.892468+05:30
13	auth	0011_update_proxy_permissions	2026-03-31 12:15:56.907167+05:30
14	auth	0012_alter_user_first_name_max_length	2026-03-31 12:15:56.924493+05:30
15	accounts	0001_initial	2026-03-31 12:15:57.107215+05:30
16	admin	0001_initial	2026-03-31 12:15:57.207931+05:30
17	admin	0002_logentry_remove_auto_add	2026-03-31 12:15:57.227206+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-03-31 12:15:57.258597+05:30
19	crm	0001_initial	2026-03-31 12:15:57.588725+05:30
20	crm	0002_designmanagerfile_marketingad_marketingbuyerintent_and_more	2026-03-31 12:15:58.202103+05:30
21	crm	0003_emailmessagerecord	2026-03-31 12:15:58.277986+05:30
22	crm	0004_emailmessagerecord_direction_and_more	2026-03-31 12:15:58.69483+05:30
23	crm	0005_emailmessagerecord_is_read_and_more	2026-03-31 12:15:58.995987+05:30
24	sessions	0001_initial	2026-03-31 12:15:59.026933+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: legaledge_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
4afi8hy1q3kjdv24kxnzoham56vrxpzx	.eJwFwUsKgzAYhdG9OP4GufdPYuxWShHxAZkotM5K995zvsN7X7b5vO5-9HW5-3XOffsMj6cwQaZQaSghIaNAGRVU0YgamnDCwsaBMy644hE3PBGJEGEiXr8_v_4a7w:1w6Swt:qo9HDqHK0-M0O232mNOTbZ3MD2rmR2oItXgTsT1HV1w	2026-04-11 18:09:31.086+05:30
5egd15sufzzxzk8ojz9rdmol7vngxqrp	.eJxVjDsOwjAQBe_iGln4l40p6TmDtfZ6cQDZUpxUiLuTSCmgnZn33iLgupSw9jyHicRFgDj9sojpmesu6IH13mRqdZmnKPdEHrbLW6P8uh7t30HBXrY1K4OGrALNbsh28Ba8g7N2nPTGEvgxc0LmPDpDEYg1sIqOyGiMicTnC-DtOK0:1w4bi3:C5Cm663AzwApUHzz0GM_qZdkZobo1I9QqWA90xEdUmw	2026-04-06 15:06:31.059+05:30
7v37whqswq56rloo0asmu7oanstxd70r	.eJxVjMsOwiAQAP9lz4ZQWpalR-9-A1leUjWQlPZk_HfTpAe9zkzmDY73rbi9p9UtEWYwcPllnsMz1UPEB9d7E6HVbV28OBJx2i5uLabX9Wz_BoV7gRmYokZl0UuUPuNElAeZrZHWMqnInqdRR5u0l5hJBhwDG042JFI4KAOfL9tnN7k:1w7Bow:osukP7NPGOaPA6rEJ3t_oJ67FfVHatXRb__fJ6RLCjg	2026-04-13 18:04:18.796+05:30
kmhgv1cjrl6jifjirt1adckxuw25mgwm	.eJxVjMsOwiAQAP9lz4ZQWpalR-9-A1leUjWQlPZk_HfTpAe9zkzmDY73rbi9p9UtEWYwcPllnsMz1UPEB9d7E6HVbV28OBJx2i5uLabX9Wz_BoV7gRmYokZl0UuUPuNElAeZrZHWMqnInqdRR5u0l5hJBhwDG042JFI4KAOfL9tnN7k:1w4xDj:uNPOE61gqqGgCmTsSW6q6tfoDR8cjMdfViyX1fsLuQA	2026-04-07 14:04:39.941+05:30
pqnn8qoab7vzmt3o4xfcb7ygxh4hbs75	.eJxVjEsOwiAUAO_y1oZA-Xfp3jMQHjykaiAp7cp4d9OkC93OTOYNIe5bDfugNSwZZhBw-WUY05PaIfIjtntnqbdtXZAdCTvtYLee6XU9279BjaPCDJNXiCIlrWS2QpDmvhBlEyOR46qgwuKlm3xRGtGoLLmwBqVD9M5KDp8v9hU4Bg:1w4iFx:1JE_uzCg3bHm-H5-EPIbiOJyggNUinFWgUFe4p7FBmk	2026-04-06 22:05:57.397+05:30
xx9ifvhwyj2ptk6qeh5l5f1wg5r8sr4n	.eJxVjMsOwiAQAP9lz4ZQWpalR-9-A1leUjWQlPZk_HfTpAe9zkzmDY73rbi9p9UtEWYwcPllnsMz1UPEB9d7E6HVbV28OBJx2i5uLabX9Wz_BoV7gRmYokZl0UuUPuNElAeZrZHWMqnInqdRR5u0l5hJBhwDG042JFI4KAOfL9tnN7k:1w4crf:SQP515P50Zup6OaE3LLLrI-vCB9xJeNuU58mlGXllUk	2026-04-06 16:20:31.515+05:30
\.


--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.accounts_customuser_groups_id_seq', 1, false);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.accounts_customuser_id_seq', 9, true);


--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.accounts_customuser_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: crm_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_activity_id_seq', 35, true);


--
-- Name: crm_calllog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_calllog_id_seq', 4, true);


--
-- Name: crm_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_company_id_seq', 5, true);


--
-- Name: crm_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_contact_id_seq', 14, true);


--
-- Name: crm_deal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_deal_id_seq', 8, true);


--
-- Name: crm_designmanagerfile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_designmanagerfile_id_seq', 1, false);


--
-- Name: crm_emailmessagerecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_emailmessagerecord_id_seq', 9, true);


--
-- Name: crm_lead_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_lead_id_seq', 15, true);


--
-- Name: crm_marketingad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingad_id_seq', 1, false);


--
-- Name: crm_marketingbuyerintent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingbuyerintent_id_seq', 1, false);


--
-- Name: crm_marketingcampaign_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingcampaign_id_seq', 1, true);


--
-- Name: crm_marketingevent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingevent_id_seq', 1, false);


--
-- Name: crm_marketingform_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingform_id_seq', 1, true);


--
-- Name: crm_marketingleadscoring_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingleadscoring_id_seq', 1, false);


--
-- Name: crm_marketingsocialpost_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_marketingsocialpost_id_seq', 1, false);


--
-- Name: crm_meeting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_meeting_id_seq', 18, true);


--
-- Name: crm_note_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_note_id_seq', 1, false);


--
-- Name: crm_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_task_id_seq', 13, true);


--
-- Name: crm_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_ticket_id_seq', 6, true);


--
-- Name: crm_useremailaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.crm_useremailaccount_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 26, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: legaledge_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: accounts_customuser accounts_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_email_key UNIQUE (email);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq UNIQUE (customuser_id, group_id);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_customuser_id_permission_9632a709_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_customuser_id_permission_9632a709_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: crm_activity crm_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_activity
    ADD CONSTRAINT crm_activity_pkey PRIMARY KEY (id);


--
-- Name: crm_calllog crm_calllog_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_calllog
    ADD CONSTRAINT crm_calllog_pkey PRIMARY KEY (id);


--
-- Name: crm_company crm_company_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_company
    ADD CONSTRAINT crm_company_pkey PRIMARY KEY (id);


--
-- Name: crm_contact crm_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_contact
    ADD CONSTRAINT crm_contact_pkey PRIMARY KEY (id);


--
-- Name: crm_deal crm_deal_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_deal
    ADD CONSTRAINT crm_deal_pkey PRIMARY KEY (id);


--
-- Name: crm_designmanagerfile crm_designmanagerfile_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_designmanagerfile
    ADD CONSTRAINT crm_designmanagerfile_pkey PRIMARY KEY (id);


--
-- Name: crm_emailmessagerecord crm_emailmessagerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_emailmessagerecord
    ADD CONSTRAINT crm_emailmessagerecord_pkey PRIMARY KEY (id);


--
-- Name: crm_lead crm_lead_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_lead
    ADD CONSTRAINT crm_lead_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingad crm_marketingad_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingad
    ADD CONSTRAINT crm_marketingad_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingbuyerintent crm_marketingbuyerintent_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingbuyerintent
    ADD CONSTRAINT crm_marketingbuyerintent_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingcampaign crm_marketingcampaign_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingcampaign
    ADD CONSTRAINT crm_marketingcampaign_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingevent crm_marketingevent_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingevent
    ADD CONSTRAINT crm_marketingevent_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingform crm_marketingform_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingform
    ADD CONSTRAINT crm_marketingform_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingleadscoring crm_marketingleadscoring_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingleadscoring
    ADD CONSTRAINT crm_marketingleadscoring_pkey PRIMARY KEY (id);


--
-- Name: crm_marketingsocialpost crm_marketingsocialpost_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingsocialpost
    ADD CONSTRAINT crm_marketingsocialpost_pkey PRIMARY KEY (id);


--
-- Name: crm_meeting crm_meeting_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_meeting
    ADD CONSTRAINT crm_meeting_pkey PRIMARY KEY (id);


--
-- Name: crm_note crm_note_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_note
    ADD CONSTRAINT crm_note_pkey PRIMARY KEY (id);


--
-- Name: crm_task crm_task_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_task
    ADD CONSTRAINT crm_task_pkey PRIMARY KEY (id);


--
-- Name: crm_ticket crm_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_ticket
    ADD CONSTRAINT crm_ticket_pkey PRIMARY KEY (id);


--
-- Name: crm_useremailaccount crm_useremailaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_useremailaccount
    ADD CONSTRAINT crm_useremailaccount_pkey PRIMARY KEY (id);


--
-- Name: crm_useremailaccount crm_useremailaccount_user_id_provider_email_a_2a79b9dd_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_useremailaccount
    ADD CONSTRAINT crm_useremailaccount_user_id_provider_email_a_2a79b9dd_uniq UNIQUE (user_id, provider, email_address);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: accounts_customuser_email_4fd8e7ce_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX accounts_customuser_email_4fd8e7ce_like ON public.accounts_customuser USING btree (email varchar_pattern_ops);


--
-- Name: accounts_customuser_groups_customuser_id_bc55088e; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX accounts_customuser_groups_customuser_id_bc55088e ON public.accounts_customuser_groups USING btree (customuser_id);


--
-- Name: accounts_customuser_groups_group_id_86ba5f9e; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX accounts_customuser_groups_group_id_86ba5f9e ON public.accounts_customuser_groups USING btree (group_id);


--
-- Name: accounts_customuser_user_permissions_customuser_id_0deaefae; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX accounts_customuser_user_permissions_customuser_id_0deaefae ON public.accounts_customuser_user_permissions USING btree (customuser_id);


--
-- Name: accounts_customuser_user_permissions_permission_id_aea3d0e5; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX accounts_customuser_user_permissions_permission_id_aea3d0e5 ON public.accounts_customuser_user_permissions USING btree (permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: crm_activity_user_id_65c68801; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_activity_user_id_65c68801 ON public.crm_activity USING btree (user_id);


--
-- Name: crm_contact_assigned_to_id_fcbbd470; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_contact_assigned_to_id_fcbbd470 ON public.crm_contact USING btree (assigned_to_id);


--
-- Name: crm_deal_assigned_to_id_44007348; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_deal_assigned_to_id_44007348 ON public.crm_deal USING btree (assigned_to_id);


--
-- Name: crm_designmanagerfile_local_id_65fc9d47; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_designmanagerfile_local_id_65fc9d47 ON public.crm_designmanagerfile USING btree (local_id);


--
-- Name: crm_designmanagerfile_local_id_65fc9d47_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_designmanagerfile_local_id_65fc9d47_like ON public.crm_designmanagerfile USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_designmanagerfile_user_id_9d3dcb32; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_designmanagerfile_user_id_9d3dcb32 ON public.crm_designmanagerfile USING btree (user_id);


--
-- Name: crm_emailmessagerecord_account_id_81196752; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_account_id_81196752 ON public.crm_emailmessagerecord USING btree (account_id);


--
-- Name: crm_emailmessagerecord_external_id_d5f34da3; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_external_id_d5f34da3 ON public.crm_emailmessagerecord USING btree (external_id);


--
-- Name: crm_emailmessagerecord_external_id_d5f34da3_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_external_id_d5f34da3_like ON public.crm_emailmessagerecord USING btree (external_id varchar_pattern_ops);


--
-- Name: crm_emailmessagerecord_owner_id_d68e0f21; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_owner_id_d68e0f21 ON public.crm_emailmessagerecord USING btree (owner_id);


--
-- Name: crm_emailmessagerecord_receiver_id_b00b0052; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_receiver_id_b00b0052 ON public.crm_emailmessagerecord USING btree (receiver_id);


--
-- Name: crm_emailmessagerecord_sender_id_eaa84e8e; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_sender_id_eaa84e8e ON public.crm_emailmessagerecord USING btree (sender_id);


--
-- Name: crm_emailmessagerecord_thread_id_c051f75a; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_thread_id_c051f75a ON public.crm_emailmessagerecord USING btree (thread_id);


--
-- Name: crm_emailmessagerecord_thread_id_c051f75a_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_emailmessagerecord_thread_id_c051f75a_like ON public.crm_emailmessagerecord USING btree (thread_id varchar_pattern_ops);


--
-- Name: crm_lead_assigned_to_id_d2e8614f; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_lead_assigned_to_id_d2e8614f ON public.crm_lead USING btree (assigned_to_id);


--
-- Name: crm_marketingad_local_id_c0601800; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingad_local_id_c0601800 ON public.crm_marketingad USING btree (local_id);


--
-- Name: crm_marketingad_local_id_c0601800_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingad_local_id_c0601800_like ON public.crm_marketingad USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingad_user_id_ee350044; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingad_user_id_ee350044 ON public.crm_marketingad USING btree (user_id);


--
-- Name: crm_marketingbuyerintent_local_id_74ba9aff; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingbuyerintent_local_id_74ba9aff ON public.crm_marketingbuyerintent USING btree (local_id);


--
-- Name: crm_marketingbuyerintent_local_id_74ba9aff_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingbuyerintent_local_id_74ba9aff_like ON public.crm_marketingbuyerintent USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingbuyerintent_user_id_0ad8849b; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingbuyerintent_user_id_0ad8849b ON public.crm_marketingbuyerintent USING btree (user_id);


--
-- Name: crm_marketingcampaign_local_id_44568778; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingcampaign_local_id_44568778 ON public.crm_marketingcampaign USING btree (local_id);


--
-- Name: crm_marketingcampaign_local_id_44568778_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingcampaign_local_id_44568778_like ON public.crm_marketingcampaign USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingcampaign_user_id_cea875f5; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingcampaign_user_id_cea875f5 ON public.crm_marketingcampaign USING btree (user_id);


--
-- Name: crm_marketingevent_local_id_94afc408; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingevent_local_id_94afc408 ON public.crm_marketingevent USING btree (local_id);


--
-- Name: crm_marketingevent_local_id_94afc408_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingevent_local_id_94afc408_like ON public.crm_marketingevent USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingevent_user_id_e2d6a069; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingevent_user_id_e2d6a069 ON public.crm_marketingevent USING btree (user_id);


--
-- Name: crm_marketingform_local_id_b98e62cc; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingform_local_id_b98e62cc ON public.crm_marketingform USING btree (local_id);


--
-- Name: crm_marketingform_local_id_b98e62cc_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingform_local_id_b98e62cc_like ON public.crm_marketingform USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingform_user_id_42d6907e; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingform_user_id_42d6907e ON public.crm_marketingform USING btree (user_id);


--
-- Name: crm_marketingleadscoring_local_id_b5850613; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingleadscoring_local_id_b5850613 ON public.crm_marketingleadscoring USING btree (local_id);


--
-- Name: crm_marketingleadscoring_local_id_b5850613_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingleadscoring_local_id_b5850613_like ON public.crm_marketingleadscoring USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingleadscoring_user_id_2824c471; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingleadscoring_user_id_2824c471 ON public.crm_marketingleadscoring USING btree (user_id);


--
-- Name: crm_marketingsocialpost_local_id_50df7942; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingsocialpost_local_id_50df7942 ON public.crm_marketingsocialpost USING btree (local_id);


--
-- Name: crm_marketingsocialpost_local_id_50df7942_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingsocialpost_local_id_50df7942_like ON public.crm_marketingsocialpost USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_marketingsocialpost_user_id_15d2f06c; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_marketingsocialpost_user_id_15d2f06c ON public.crm_marketingsocialpost USING btree (user_id);


--
-- Name: crm_note_local_id_966eefba; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_note_local_id_966eefba ON public.crm_note USING btree (local_id);


--
-- Name: crm_note_local_id_966eefba_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_note_local_id_966eefba_like ON public.crm_note USING btree (local_id varchar_pattern_ops);


--
-- Name: crm_note_user_id_bb9a91c7; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_note_user_id_bb9a91c7 ON public.crm_note USING btree (user_id);


--
-- Name: crm_task_assigned_to_id_1983fb7b; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_task_assigned_to_id_1983fb7b ON public.crm_task USING btree (assigned_to_id);


--
-- Name: crm_useremailaccount_user_id_a048e0b9; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX crm_useremailaccount_user_id_a048e0b9 ON public.crm_useremailaccount USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: legaledge_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_customuser_user_permissions accounts_customuser__customuser_id_0deaefae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser__customuser_id_bc55088e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_user_permissions accounts_customuser__permission_id_aea3d0e5_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_activity crm_activity_user_id_65c68801_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_activity
    ADD CONSTRAINT crm_activity_user_id_65c68801_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_contact crm_contact_assigned_to_id_fcbbd470_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_contact
    ADD CONSTRAINT crm_contact_assigned_to_id_fcbbd470_fk_accounts_customuser_id FOREIGN KEY (assigned_to_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_deal crm_deal_assigned_to_id_44007348_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_deal
    ADD CONSTRAINT crm_deal_assigned_to_id_44007348_fk_accounts_customuser_id FOREIGN KEY (assigned_to_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_designmanagerfile crm_designmanagerfil_user_id_9d3dcb32_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_designmanagerfile
    ADD CONSTRAINT crm_designmanagerfil_user_id_9d3dcb32_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_emailmessagerecord crm_emailmessagereco_account_id_81196752_fk_crm_usere; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_emailmessagerecord
    ADD CONSTRAINT crm_emailmessagereco_account_id_81196752_fk_crm_usere FOREIGN KEY (account_id) REFERENCES public.crm_useremailaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_emailmessagerecord crm_emailmessagereco_owner_id_d68e0f21_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_emailmessagerecord
    ADD CONSTRAINT crm_emailmessagereco_owner_id_d68e0f21_fk_accounts_ FOREIGN KEY (owner_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_emailmessagerecord crm_emailmessagereco_receiver_id_b00b0052_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_emailmessagerecord
    ADD CONSTRAINT crm_emailmessagereco_receiver_id_b00b0052_fk_accounts_ FOREIGN KEY (receiver_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_emailmessagerecord crm_emailmessagereco_sender_id_eaa84e8e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_emailmessagerecord
    ADD CONSTRAINT crm_emailmessagereco_sender_id_eaa84e8e_fk_accounts_ FOREIGN KEY (sender_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_lead crm_lead_assigned_to_id_d2e8614f_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_lead
    ADD CONSTRAINT crm_lead_assigned_to_id_d2e8614f_fk_accounts_customuser_id FOREIGN KEY (assigned_to_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingad crm_marketingad_user_id_ee350044_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingad
    ADD CONSTRAINT crm_marketingad_user_id_ee350044_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingbuyerintent crm_marketingbuyerin_user_id_0ad8849b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingbuyerintent
    ADD CONSTRAINT crm_marketingbuyerin_user_id_0ad8849b_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingcampaign crm_marketingcampaig_user_id_cea875f5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingcampaign
    ADD CONSTRAINT crm_marketingcampaig_user_id_cea875f5_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingevent crm_marketingevent_user_id_e2d6a069_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingevent
    ADD CONSTRAINT crm_marketingevent_user_id_e2d6a069_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingform crm_marketingform_user_id_42d6907e_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingform
    ADD CONSTRAINT crm_marketingform_user_id_42d6907e_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingleadscoring crm_marketingleadsco_user_id_2824c471_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingleadscoring
    ADD CONSTRAINT crm_marketingleadsco_user_id_2824c471_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_marketingsocialpost crm_marketingsocialp_user_id_15d2f06c_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_marketingsocialpost
    ADD CONSTRAINT crm_marketingsocialp_user_id_15d2f06c_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_note crm_note_user_id_bb9a91c7_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_note
    ADD CONSTRAINT crm_note_user_id_bb9a91c7_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_task crm_task_assigned_to_id_1983fb7b_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_task
    ADD CONSTRAINT crm_task_assigned_to_id_1983fb7b_fk_accounts_customuser_id FOREIGN KEY (assigned_to_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crm_useremailaccount crm_useremailaccount_user_id_a048e0b9_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.crm_useremailaccount
    ADD CONSTRAINT crm_useremailaccount_user_id_a048e0b9_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: legaledge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO legaledge_user;


--
-- PostgreSQL database dump complete
--

\unrestrict FQqiceE6ydKhePOKMLuCrWNIdQXxQ3LoQ3cUY1VCUgbFin55EXrXTr6MQXvopg9

